# roles/tomcat/tasks/main.yml
---
- name: Install default JDK
  apt: 
    name: default-jdk
    state: present

- name: Create tomcat group
  group:
    name: tomcat
    state: present

- name: Create tomcat user
  user:
    name: tomcat
    group: tomcat
    system: yes
    home: /opt/tomcat

- name: Download Tomcat
  get_url:
    url: "{{ tomcat_download_url }}"
    dest: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"

- name: Ensure /opt/tomcat is available
  file:
    path: /opt/tomcat
    state: directory

- name: Unpack Tomcat
  unarchive:
    src: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"
    dest: /opt/tomcat
    remote_src: yes
    owner: tomcat
    group: tomcat
    creates: "/opt/tomcat/apache-tomcat-{{ tomcat_version }}"

- name: Set the symlink for latest tomcat
  file:
    src: "/opt/tomcat/apache-tomcat-{{ tomcat_version }}"
    dest: /opt/tomcat/latest
    state: link

- name: Set permissions
  file:
    path: "{{ item.path }}"
    owner: tomcat
    group: tomcat
    mode: "{{ item.mode }}"
  loop:
    - { path: '/opt/tomcat', mode: '0755' }
    - { path: '/opt/tomcat/latest/conf', mode: '0750' }
  loop_control:
    loop_var: item

- name: Deploy systemd service file
  template:
    src: tomcat.service.j2
    dest: /etc/systemd/system/tomcat.service

- name: Enable and start tomcat
  systemd:
    name: tomcat
    enabled: yes
    state: started
